version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
